<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class MajorsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {


        \DB::table('majors')->delete();

        \DB::table('majors')->insert(array (
            0 =>
                array (
                    'id' => 184,
                    'name' => 'Giáo dục Tiểu học',
                    'code' => '7140202',
                    'reference_score' => 27.75,
                    'entrance_score' => 27.75,
                    'subjects_combination' => '["A00", "C01", "D01", "D03"]',
                    'information' => '<a href="https://tuyensinh.ctu.edu.vn/gioi-thieu-nganh/475-giao-duc-tieu-hoc" target="_blank">Xem Thông Tin</a>',
                    'tuition' => '13,2',
                    'total_credit' => NULL,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                    'target' => 80,
                ),
            1 =>
                array (
                    'id' => 185,
                    'name' => 'Giáo dục Công dân',
                    'code' => '7140204',
                    'reference_score' => 25.25,
                    'entrance_score' => 25.25,
                    'subjects_combination' => '["C00", "C19", "D14", "D15"]',
                    'information' => '<a href="https://tuyensinh.ctu.edu.vn/gioi-thieu-nganh/537-giao-duc-cong-dan" target="_blank">Xem Thông Tin</a>',
                    'tuition' => '13,2',
                    'total_credit' => NULL,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                    'target' => 60,
                ),
            2 =>
                array (
                    'id' => 186,
                    'name' => 'Giáo dục Thể chất',
                    'code' => '7140206',
                    'reference_score' => 25.75,
                    'entrance_score' => 25.75,
                    'subjects_combination' => '["T00", "T01", "T06"]',
                    'information' => '<a href="https://tuyensinh.ctu.edu.vn/gioi-thieu-nganh/550-giao-duc-the-chat" target="_blank">Xem Thông Tin</a>',
                    'tuition' => '13,2',
                    'total_credit' => NULL,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                    'target' => 60,
                ),
            3 =>
                array (
                    'id' => 187,
                    'name' => 'Sư phạm Toán học',
                    'code' => '7140209',
                    'reference_score' => 29.25,
                    'entrance_score' => 29.25,
                    'subjects_combination' => '["A00", "A01", "B08", "D07"]',
                    'information' => '<a href="https://tuyensinh.ctu.edu.vn/gioi-thieu-nganh/473-su-pham-toan-hoc" target="_blank">Xem Thông Tin</a>',
                    'tuition' => '13,2',
                    'total_credit' => NULL,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                    'target' => 80,
                ),
            4 =>
                array (
                    'id' => 188,
                    'name' => 'Sư phạm Tin học',
                    'code' => '7140210',
                    'reference_score' => 24.0,
                    'entrance_score' => 24.0,
                    'subjects_combination' => '["A00", "A01", "D01", "D07"]',
                    'information' => '<a href="https://tuyensinh.ctu.edu.vn/gioi-thieu-nganh/749-su-pham-tin-hoc" target="_blank">Xem Thông Tin</a>',
                    'tuition' => '13,2',
                    'total_credit' => NULL,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                    'target' => 60,
                ),
            5 =>
                array (
                    'id' => 189,
                    'name' => 'Sư phạm Vật lý',
                    'code' => '7140211',
                    'reference_score' => 27.75,
                    'entrance_score' => 27.75,
                    'subjects_combination' => '["A00", "A01", "A02", "D29"]',
                    'information' => '<a href="https://tuyensinh.ctu.edu.vn/gioi-thieu-nganh/474-su-pham-vat-ly" target="_blank">Xem Thông Tin</a>',
                    'tuition' => '13,2',
                    'total_credit' => NULL,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                    'target' => 60,
                ),
            6 =>
                array (
                    'id' => 190,
                    'name' => 'Sư phạm Hóa học',
                    'code' => '7140212',
                    'reference_score' => 29.0,
                    'entrance_score' => 29.0,
                    'subjects_combination' => '["A00", "B00", "D07", "D24"]',
                    'information' => '<a href="https://tuyensinh.ctu.edu.vn/gioi-thieu-nganh/476-su-pham-hoa-hoc" target="_blank">Xem Thông Tin</a>',
                    'tuition' => '13,2',
                    'total_credit' => NULL,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                    'target' => 60,
                ),
            7 =>
                array (
                    'id' => 191,
                    'name' => 'Sư phạm Sinh học',
                    'code' => '7140213',
                    'reference_score' => 25.0,
                    'entrance_score' => 25.0,
                    'subjects_combination' => '["B00", "B08"]',
                    'information' => '<a href="https://tuyensinh.ctu.edu.vn/gioi-thieu-nganh/477-su-pham-sinh-hoc" target="_blank">Xem Thông Tin</a>',
                    'tuition' => '13,2',
                    'total_credit' => NULL,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                    'target' => 60,
                ),
            8 =>
                array (
                    'id' => 192,
                    'name' => 'Sư phạm Ngữ văn',
                    'code' => '7140217',
                    'reference_score' => 27.75,
                    'entrance_score' => 27.75,
                    'subjects_combination' => '["C00", "D14", "D15"]',
                    'information' => '<a href="https://tuyensinh.ctu.edu.vn/gioi-thieu-nganh/478-su-pham-ngu-van" target="_blank">Xem Thông Tin</a>',
                    'tuition' => '13,2',
                    'total_credit' => NULL,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                    'target' => 80,
                ),
            9 =>
                array (
                    'id' => 193,
                    'name' => 'Sư phạm Lịch sử',
                    'code' => '7140218',
                    'reference_score' => 26.0,
                    'entrance_score' => 26.0,
                    'subjects_combination' => '["C00", "D14", "D64"]',
                    'information' => '<a href="https://tuyensinh.ctu.edu.vn/gioi-thieu-nganh/479-su-pham-lich-su" target="_blank">Xem Thông Tin</a>',
                    'tuition' => '13,2',
                    'total_credit' => NULL,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                    'target' => 60,
                ),
            10 =>
                array (
                    'id' => 194,
                    'name' => 'Sư phạm Địa lý',
                    'code' => '7140219',
                    'reference_score' => 26.0,
                    'entrance_score' => 26.0,
                    'subjects_combination' => '["C00", "C04", "D15", "D44"]',
                    'information' => '<a href="https://tuyensinh.ctu.edu.vn/gioi-thieu-nganh/480-su-pham-dia-ly" target="_blank">Xem Thông Tin</a>',
                    'tuition' => '13,2',
                    'total_credit' => NULL,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                    'target' => 60,
                ),
            11 =>
                array (
                    'id' => 195,
                    'name' => 'Sư phạm Tiếng Anh',
                    'code' => '7140231',
                    'reference_score' => 28.0,
                    'entrance_score' => 28.0,
                    'subjects_combination' => '["D01", "D14", "D15"]',
                    'information' => '<a href="https://tuyensinh.ctu.edu.vn/gioi-thieu-nganh/481-su-pham-tieng-anh" target="_blank">Xem Thông Tin</a>',
                    'tuition' => '13,2',
                    'total_credit' => NULL,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                    'target' => 80,
                ),
            12 =>
                array (
                    'id' => 196,
                    'name' => 'Sư phạm Tiếng Pháp',
                    'code' => '7140233',
                    'reference_score' => 24.25,
                    'entrance_score' => 24.25,
                    'subjects_combination' => '["D01", "D03", "D14", "D64"]',
                    'information' => '<a href="https://tuyensinh.ctu.edu.vn/gioi-thieu-nganh/482-su-pham-tieng-phap" target="_blank">Xem Thông Tin</a>',
                    'tuition' => '13,2',
                    'total_credit' => NULL,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                    'target' => 60,
                ),
            13 =>
                array (
                    'id' => 197,
                    'name' => 'Công nghệ kỹ thuật hóa học',
                    'code' => '7510401',
                    'reference_score' => 26.0,
                    'entrance_score' => 26.0,
                    'subjects_combination' => '["A00", "A01", "B00", "D07"]',
                    'information' => '<a href="https://tuyensinh.ctu.edu.vn/gioi-thieu-nganh/551-cong-nghe-ky-thuat-hoa-hoc" target="_blank">Xem Thông Tin</a>',
                    'tuition' => '15,2',
                    'total_credit' => NULL,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                    'target' => 100,
                ),
            14 =>
                array (
                    'id' => 198,
                    'name' => 'Kỹ thuật vật liệu',
                    'code' => '7520309',
                    'reference_score' => 20.75,
                    'entrance_score' => 20.75,
                    'subjects_combination' => '["A00", "A01", "B00", "D07"]',
                    'information' => '<a href="https://tuyensinh.ctu.edu.vn/gioi-thieu-nganh/744-ky-thuat-vat-lieu" target="_blank">Xem Thông Tin</a>',
                    'tuition' => '15,2',
                    'total_credit' => NULL,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                    'target' => 40,
                ),
            15 =>
                array (
                    'id' => 199,
                    'name' => 'Quản lý công nghiệp',
                    'code' => '7510601',
                    'reference_score' => 26.75,
                    'entrance_score' => 26.75,
                    'subjects_combination' => '["A00", "A01", "D01"]',
                    'information' => '<a href="https://tuyensinh.ctu.edu.vn/gioi-thieu-nganh/491-quan-ly-cong-nghiep" target="_blank">Xem Thông Tin</a>',
                    'tuition' => '15,2',
                    'total_credit' => NULL,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                    'target' => 80,
                ),
            16 =>
                array (
                    'id' => 200,
                    'name' => 'Kỹ thuật cơ khí',
                    'code' => '7520103',
                    'reference_score' => 26.75,
                    'entrance_score' => 26.75,
                    'subjects_combination' => '["A00", "A01"]',
                    'information' => 'Ngành Kỹ thuật cơ khí có hai chuyên ngành: <br>Cơ khí chế tạo máy: <a href="https://tuyensinh.ctu.edu.vn/gioi-thieu-nganh/769-ky-thuat-co-khi-co-khi-che-tao-may" target="_blank">Xem Thông Tin</a> <br>Cơ khí Ô tô: <a href="https://tuyensinh.ctu.edu.vn/gioi-thieu-nganh/771-ky-thuat-co-khi-co-khi-oto" target="_blank">Xem Thông Tin</a>',
                    'tuition' => '15,2',
                    'total_credit' => NULL,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                    'target' => 120,
                ),
            17 =>
                array (
                    'id' => 201,
                    'name' => 'Kỹ thuật cơ điện tử',
                    'code' => '7520114',
                    'reference_score' => 25.5,
                    'entrance_score' => 25.5,
                    'subjects_combination' => '["A00", "A01"]',
                    'information' => '<a href="https://tuyensinh.ctu.edu.vn/gioi-thieu-nganh/490-ky-thuat-co-dien-tu" target="_blank">Xem Thông Tin</a>',
                    'tuition' => '15,2',
                    'total_credit' => NULL,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                    'target' => 70,
                ),
            18 =>
                array (
                    'id' => 202,
                    'name' => 'Kỹ thuật điều khiển và tự động hóa',
                    'code' => '7520216',
                    'reference_score' => 26.0,
                    'entrance_score' => 26.0,
                    'subjects_combination' => '["A00", "A01"]',
                    'information' => '<a href="https://tuyensinh.ctu.edu.vn/gioi-thieu-nganh/488-ky-thuat-dieu-khien-va-tu-dong-hoa" target="_blank">Xem Thông Tin</a>',
                    'tuition' => '15,2',
                    'total_credit' => NULL,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                    'target' => 70,
                ),
            19 =>
                array (
                    'id' => 203,
                    'name' => 'Kỹ thuật điện tử - viễn thông',
                    'code' => '7520207',
                    'reference_score' => 23.5,
                    'entrance_score' => 23.5,
                    'subjects_combination' => '["A00", "A01"]',
                    'information' => '<a href="https://tuyensinh.ctu.edu.vn/gioi-thieu-nganh/486-ky-thuat-dien-tu-vien-thong" target="_blank">Xem Thông Tin</a>',
                    'tuition' => '15,2',
                    'total_credit' => NULL,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                    'target' => 70,
                ),
            20 =>
                array (
                    'id' => 204,
                    'name' => 'Kỹ thuật điện',
                    'code' => '7520201',
                    'reference_score' => 25.25,
                    'entrance_score' => 25.25,
                    'subjects_combination' => '["A00", "A01", "D07"]',
                    'information' => '<a href="https://tuyensinh.ctu.edu.vn/gioi-thieu-nganh/489-ky-thuat-dien" target="_blank">Xem Thông Tin</a>',
                    'tuition' => '15,2',
                    'total_credit' => NULL,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                    'target' => 70,
                ),
            21 =>
                array (
                    'id' => 205,
                    'name' => 'Kỹ thuật xây dựng',
                    'code' => '7580201',
                    'reference_score' => 25.25,
                    'entrance_score' => 25.25,
                    'subjects_combination' => '["A00", "A01"]',
                    'information' => '<a href="https://tuyensinh.ctu.edu.vn/gioi-thieu-nganh/485-ky-thuat-xay-dung" target="_blank">Xem Thông Tin</a>',
                    'tuition' => '15,2',
                    'total_credit' => NULL,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                    'target' => 140,
                ),
            22 =>
                array (
                    'id' => 206,
                    'name' => 'Kỹ thuật xây dựng công trình thủy',
                    'code' => '7580202',
                    'reference_score' => 19.5,
                    'entrance_score' => 19.5,
                    'subjects_combination' => '["A00", "A01"]',
                    'information' => '<a href="https://tuyensinh.ctu.edu.vn/gioi-thieu-nganh/753-ky-thuat-xay-dung-cong-trinh-thuy" target="_blank">Xem Thông Tin</a>',
                    'tuition' => '15,2',
                    'total_credit' => NULL,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                    'target' => 60,
                ),
            23 =>
                array (
                    'id' => 207,
                    'name' => 'Kỹ thuật xây dựng công trình giao thông',
                    'code' => '7580205',
                    'reference_score' => 21.25,
                    'entrance_score' => 21.25,
                    'subjects_combination' => '["A00", "A01"]',
                    'information' => '<a href="https://tuyensinh.ctu.edu.vn/gioi-thieu-nganh/754-ky-thuat-xay-dung-cong-trinh-giao-thong" target="_blank">Xem Thông Tin</a>',
                    'tuition' => '15,2',
                    'total_credit' => NULL,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                    'target' => 60,
                ),
            24 =>
                array (
                    'id' => 208,
                    'name' => 'Khoa học máy tính',
                    'code' => '7480101',
                    'reference_score' => 27.0,
                    'entrance_score' => 27.0,
                    'subjects_combination' => '["A00", "A01"]',
                    'information' => '<a href="https://tuyensinh.ctu.edu.vn/gioi-thieu-nganh/493-khoa-hoc-may-tinh" target="_blank">Xem Thông Tin</a>',
                    'tuition' => '15,2',
                    'total_credit' => NULL,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                    'target' => 60,
                ),
            25 =>
                array (
                    'id' => 209,
                    'name' => 'Kỹ thuật máy tính',
                    'code' => '7480106',
                    'reference_score' => 24.5,
                    'entrance_score' => 24.5,
                    'subjects_combination' => '["A00", "A01"]',
                    'information' => '<a href="https://tuyensinh.ctu.edu.vn/gioi-thieu-nganh/752-ky-thuat-may-tinh" target="_blank">Xem Thông Tin</a>',
                    'tuition' => '15,2',
                    'total_credit' => NULL,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                    'target' => 60,
                ),
            26 =>
                array (
                    'id' => 210,
                    'name' => 'Mạng máy tính và truyền thông dữ liệu',
                    'code' => '7480102',
                    'reference_score' => 25.25,
                    'entrance_score' => 25.25,
                    'subjects_combination' => '["A00", "A01"]',
                    'information' => '<a href="https://tuyensinh.ctu.edu.vn/gioi-thieu-nganh/494-m-ng-may-tinh-va-truy-n-thong-d-li-u" target="_blank">Xem Thông Tin</a>',
                    'tuition' => '15,2',
                    'total_credit' => NULL,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                    'target' => 60,
                ),
            27 =>
                array (
                    'id' => 211,
                    'name' => 'Kỹ thuật phần mềm',
                    'code' => '7480103',
                    'reference_score' => 27.5,
                    'entrance_score' => 27.5,
                    'subjects_combination' => '["A00", "A01"]',
                    'information' => '<a href="https://tuyensinh.ctu.edu.vn/gioi-thieu-nganh/495-ky-thuat-phan-mem" target="_blank">Xem Thông Tin</a>',
                    'tuition' => '15,2',
                    'total_credit' => NULL,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                    'target' => 60,
                ),
            28 =>
                array (
                    'id' => 212,
                    'name' => 'Hệ thống thông tin',
                    'code' => '7480104',
                    'reference_score' => 25.75,
                    'entrance_score' => 25.75,
                    'subjects_combination' => '["A00", "A01"]',
                    'information' => '<a href="https://tuyensinh.ctu.edu.vn/gioi-thieu-nganh/552-he-thong-thong-tin" target="_blank">Xem Thông Tin</a>',
                    'tuition' => '15,2',
                    'total_credit' => NULL,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                    'target' => 60,
                ),
            29 =>
                array (
                    'id' => 213,
                    'name' => 'Công nghệ thông tin',
                    'code' => '7480201',
                    'reference_score' => 28.5,
                    'entrance_score' => 28.5,
                    'subjects_combination' => '["A00", "A01"]',
                    'information' => '<a href="https://tuyensinh.ctu.edu.vn/gioi-thieu-nganh/496-cong-nghe-thong-tin" target="_blank">Xem Thông Tin</a>',
                    'tuition' => '15,2',
                    'total_credit' => NULL,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                    'target' => 60,
                ),
            30 =>
                array (
                    'id' => 214,
                    'name' => 'Công nghệ thông tin - học tại khu Hòa An',
                    'code' => '7480201H',
                    'reference_score' => 24.25,
                    'entrance_score' => 24.25,
                    'subjects_combination' => '["A00", "A01"]',
                    'information' => '<a href="https://tuyensinh.ctu.edu.vn/gioi-thieu-nganh/847-cong-nghe-thong-tin-2" target="_blank">Xem Thông Tin</a>',
                    'tuition' => '15,2',
                    'total_credit' => NULL,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                    'target' => 40,
                ),
            31 =>
                array (
                    'id' => 215,
                    'name' => 'Kế toán',
                    'code' => '7340301',
                    'reference_score' => 28.5,
                    'entrance_score' => 28.5,
                    'subjects_combination' => '["A00", "A01", "C02", "D01"]',
                    'information' => '<a href="https://tuyensinh.ctu.edu.vn/gioi-thieu-nganh/499-ke-toan" target="_blank">Xem Thông Tin</a>',
                    'tuition' => '13,2',
                    'total_credit' => NULL,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                    'target' => 60,
                ),
            32 =>
                array (
                    'id' => 216,
                    'name' => 'Kiểm toán',
                    'code' => '7340302',
                    'reference_score' => 27.5,
                    'entrance_score' => 27.5,
                    'subjects_combination' => '["A00", "A01", "C02", "D01"]',
                    'information' => '<a href="https://tuyensinh.ctu.edu.vn/gioi-thieu-nganh/500-kiem-toan" target="_blank">Xem Thông Tin</a>',
                    'tuition' => '13,2',
                    'total_credit' => NULL,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                    'target' => 60,
                ),
            33 =>
                array (
                    'id' => 217,
                    'name' => 'Tài chính - Ngân hàng',
                    'code' => '7340201',
                    'reference_score' => 28.75,
                    'entrance_score' => 28.75,
                    'subjects_combination' => '["A00", "A01", "C02", "D01"]',
                    'information' => '<a href="https://tuyensinh.ctu.edu.vn/gioi-thieu-nganh/502-tai-chinh-ngan-hang" target="_blank">Xem Thông Tin</a>',
                    'tuition' => '13,2',
                    'total_credit' => NULL,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                    'target' => 60,
                ),
            34 =>
                array (
                    'id' => 218,
                    'name' => 'Quản trị kinh doanh',
                    'code' => '7340101',
                    'reference_score' => 28.75,
                    'entrance_score' => 28.75,
                    'subjects_combination' => '["A00", "A01", "C02", "D01"]',
                    'information' => '<a href="https://tuyensinh.ctu.edu.vn/gioi-thieu-nganh/888-quan-tri-kinh-doanh" target="_blank">Xem Thông Tin</a>',
                    'tuition' => '13,2',
                    'total_credit' => NULL,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                    'target' => 80,
                ),
            35 =>
                array (
                    'id' => 219,
                    'name' => 'Quản trị kinh doanh - học tại khu Hòa An',
                    'code' => '7340101H',
                    'reference_score' => 26.25,
                    'entrance_score' => 26.25,
                    'subjects_combination' => '["A00", "A01", "C02", "D01"]',
                    'information' => '<a href="https://tuyensinh.ctu.edu.vn/gioi-thieu-nganh/844-quan-tri-kinh-doanh-h" target="_blank">Xem Thông Tin</a>',
                    'tuition' => '13,2',
                    'total_credit' => NULL,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                    'target' => 40,
                ),
            36 =>
                array (
                    'id' => 220,
                    'name' => 'Quản trị dịch vụ du lịch và lữ hành',
                    'code' => '7810103',
                    'reference_score' => 28.0,
                    'entrance_score' => 28.0,
                    'subjects_combination' => '["A00", "A01", "C02", "D01"]',
                    'information' => '<a href="https://tuyensinh.ctu.edu.vn/gioi-thieu-nganh/504-quan-tri-dich-vu-du-lich-va-lu-hanh" target="_blank">Xem Thông Tin</a>',
                    'tuition' => '12,6',
                    'total_credit' => NULL,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                    'target' => 80,
                ),
            37 =>
                array (
                    'id' => 221,
                    'name' => 'Marketing',
                    'code' => '7340115',
                    'reference_score' => 29.0,
                    'entrance_score' => 29.0,
                    'subjects_combination' => '["A00", "A01", "C02", "D01"]',
                    'information' => '<a href="https://tuyensinh.ctu.edu.vn/gioi-thieu-nganh/505-marketing" target="_blank">Xem Thông Tin</a>',
                    'tuition' => '13,2',
                    'total_credit' => NULL,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                    'target' => 60,
                ),
            38 =>
                array (
                    'id' => 222,
                    'name' => 'Kinh doanh thương mại',
                    'code' => '7340121',
                    'reference_score' => 28.25,
                    'entrance_score' => 28.25,
                    'subjects_combination' => '["A00", "A01", "C02", "D01"]',
                    'information' => '<a href="https://tuyensinh.ctu.edu.vn/gioi-thieu-nganh/750-kinh-doanh-thuong-mai" target="_blank">Xem Thông Tin</a>',
                    'tuition' => '13,2',
                    'total_credit' => NULL,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                    'target' => 80,
                ),
            39 =>
                array (
                    'id' => 223,
                    'name' => 'Kinh doanh quốc tế',
                    'code' => '7340120',
                    'reference_score' => 29.0,
                    'entrance_score' => 29.0,
                    'subjects_combination' => '["A00", "A01", "C02", "D01"]',
                    'information' => '<a href="https://tuyensinh.ctu.edu.vn/gioi-thieu-nganh/508-kinh-doanh-quoc-te" target="_blank">Xem Thông Tin</a>',
                    'tuition' => '13,2',
                    'total_credit' => NULL,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                    'target' => 80,
                ),
            40 =>
                array (
                    'id' => 224,
                    'name' => 'Kinh doanh nông nghiệp - học tại khu Hòa An',
                    'code' => '7620114H',
                    'reference_score' => 19.5,
                    'entrance_score' => 19.5,
                    'subjects_combination' => '["A00", "A01", "C02", "D01"]',
                    'information' => '<a href="https://tuyensinh.ctu.edu.vn/gioi-thieu-nganh/566-kinh-doanh-nong-nghiep" target="_blank">Xem Thông Tin</a>',
                    'tuition' => '15,2',
                    'total_credit' => NULL,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                    'target' => 120,
                ),
            41 =>
                array (
                    'id' => 225,
                    'name' => 'Kinh tế',
                    'code' => '7310101',
                    'reference_score' => 28.25,
                    'entrance_score' => 28.25,
                    'subjects_combination' => '["A00", "A01", "C02", "D01"]',
                    'information' => '<a href="https://tuyensinh.ctu.edu.vn/gioi-thieu-nganh/498-kinh-te" target="_blank">Xem Thông Tin</a>',
                    'tuition' => '12,6',
                    'total_credit' => NULL,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                    'target' => 80,
                ),
            42 =>
                array (
                    'id' => 226,
                    'name' => 'Kinh tế nông nghiệp',
                    'code' => '7620115',
                    'reference_score' => 26.0,
                    'entrance_score' => 26.0,
                    'subjects_combination' => '["A00", "A01", "C02", "D01"]',
                    'information' => '<a href="https://tuyensinh.ctu.edu.vn/gioi-thieu-nganh/507-kinh-te-nong-nghiep" target="_blank">Xem Thông Tin</a>',
                    'tuition' => '15,2',
                    'total_credit' => NULL,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                    'target' => 140,
                ),
            43 =>
                array (
                    'id' => 227,
                    'name' => 'Kinh tế nông nghiệp - học tại khu Hòa An',
                    'code' => '7620115H',
                    'reference_score' => 22.0,
                    'entrance_score' => 22.0,
                    'subjects_combination' => '["A00", "A01", "C02", "D01"]',
                    'information' => '<a href="https://tuyensinh.ctu.edu.vn/gioi-thieu-nganh/845-kinh-te-nong-nghiep-h" target="_blank">Xem Thông Tin</a>',
                    'tuition' => '15,2',
                    'total_credit' => NULL,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                    'target' => 70,
                ),
            44 =>
                array (
                    'id' => 228,
                    'name' => 'Kinh tế tài nguyên thiên nhiên',
                    'code' => '7850102',
                    'reference_score' => 24.5,
                    'entrance_score' => 24.5,
                    'subjects_combination' => '["A00", "A01", "C02", "D01"]',
                    'information' => '<a href="https://tuyensinh.ctu.edu.vn/gioi-thieu-nganh/509-kinh-te-tai-nguyen-thien-nhien" target="_blank">Xem Thông Tin</a>',
                    'tuition' => '12,6',
                    'total_credit' => NULL,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                    'target' => 80,
                ),
            45 =>
                array (
                    'id' => 229,
                    'name' => 'Luật',
                    'code' => '7380101',
                    'reference_score' => 27.25,
                    'entrance_score' => 27.25,
                    'subjects_combination' => '["A00", "C00", "4D01", "D03"]',
                    'information' => 'Ngành Luật có 3 chuyên ngành:<br>Luật Hành chính: <a href="https://tuyensinh.ctu.edu.vn/gioi-thieu-nganh/763-luat-luat-hanh-chinh" target="_blank">Xem Thông Tin</a><br>Luật Tư pháp: <a href="https://tuyensinh.ctu.edu.vn/gioi-thieu-nganh/765-luat-luat-tu-phap" target="_blank">Xem Thông Tin</a><br>Luật thương mại: <a href="https://tuyensinh.ctu.edu.vn/gioi-thieu-nganh/764-luat-luat-thuong-mai" target="_blank">Xem Thông Tin</a>',
                    'tuition' => '13,2',
                    'total_credit' => NULL,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                    'target' => 200,
                ),
            46 =>
                array (
                    'id' => 230,
                    'name' => 'Luật (chuyên ngành Luật Hành chính) - học tại khu Hòa An',
                    'code' => '7380101H',
                    'reference_score' => 27.75,
                    'entrance_score' => 27.75,
                    'subjects_combination' => '["A00", "C00", "D01", "D03"]',
                    'information' => '<a href="https://tuyensinh.ctu.edu.vn/gioi-thieu-nganh/846-luat-luat-hanh-chinh-h" target="_blank">Xem Thông Tin</a>',
                    'tuition' => '13,2',
                    'total_credit' => NULL,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                    'target' => 40,
                ),
            47 =>
                array (
                    'id' => 231,
                    'name' => 'Công nghệ thực phẩm',
                    'code' => '7540101',
                    'reference_score' => 28.0,
                    'entrance_score' => 28.0,
                    'subjects_combination' => '["A00", "A01", "B00", "D07"]',
                    'information' => '<a href="https://tuyensinh.ctu.edu.vn/gioi-thieu-nganh/464-cong-nghe-thuc-pham" target="_blank">Xem Thông Tin</a>',
                    'tuition' => '15,2',
                    'total_credit' => NULL,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                    'target' => 170,
                ),
            48 =>
                array (
                    'id' => 232,
                    'name' => 'Công nghệ chế biến thủy sản',
                    'code' => '7540105',
                    'reference_score' => 24.25,
                    'entrance_score' => 24.25,
                    'subjects_combination' => '["A00", "A01", "B00", "D07"]',
                    'information' => '<a href="https://tuyensinh.ctu.edu.vn/gioi-thieu-nganh/518-cong-nghe-che-bien-thuy-san" target="_blank">Xem Thông Tin</a>',
                    'tuition' => '15,2',
                    'total_credit' => NULL,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                    'target' => 140,
                ),
            49 =>
                array (
                    'id' => 233,
                    'name' => 'Công nghệ sau thu hoạch',
                    'code' => '7540104',
                    'reference_score' => 19.5,
                    'entrance_score' => 19.5,
                    'subjects_combination' => '["A00", "A01", "B00", "D07"]',
                    'information' => '<a href="https://tuyensinh.ctu.edu.vn/gioi-thieu-nganh/564-cong-nghe-sau-thu-hoach" target="_blank">Xem Thông Tin</a>',
                    'tuition' => '15,2',
                    'total_credit' => NULL,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                    'target' => 40,
                ),
            50 =>
                array (
                    'id' => 234,
                    'name' => 'Chăn nuôi',
                    'code' => '7620105',
                    'reference_score' => 20.0,
                    'entrance_score' => 20.0,
                    'subjects_combination' => '["A00", "A02", "B00", "B08"]',
                    'information' => '<a href="https://tuyensinh.ctu.edu.vn/gioi-thieu-nganh/465-chan-nuo" target="_blank">Xem Thông Tin</a>',
                    'tuition' => '15,2',
                    'total_credit' => NULL,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                    'target' => 140,
                ),
            51 =>
                array (
                    'id' => 235,
                    'name' => 'Thú y',
                    'code' => '7640101',
                    'reference_score' => 27.75,
                    'entrance_score' => 27.75,
                    'subjects_combination' => '["B00", "A02", "D07", "B08"]',
                    'information' => '<a href="https://tuyensinh.ctu.edu.vn/gioi-thieu-nganh/466-thu-y" target="_blank">Xem Thông Tin</a>',
                    'tuition' => '15,2',
                    'total_credit' => NULL,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                    'target' => 120,
                ),
            52 =>
                array (
                    'id' => 236,
                    'name' => 'Khoa học cây trồng',
                    'code' => '7620110',
                    'reference_score' => 19.5,
                    'entrance_score' => 19.5,
                    'subjects_combination' => '["A02", "B00", "B08", "D07"]',
                    'information' => 'Ngành Khoa học cây trồng có 2 chuyên ngành:<br>Khoa học cây trồng: <a href="https://tuyensinh.ctu.edu.vn/gioi-thieu-nganh/774-khoa-hoc-cay-trong-khoa-hoc-cay-trong" target="_blank">Xem Thông Tin</a><br>Nông nghiệp công nghệ cao: https://tuyensinh.ctu.edu.vn/gioi-thieu-nganh/906-nong-nghiep-cong-nghe-cao" target="_blank">Xem Thông Tin</a>',
                    'tuition' => '15,2',
                    'total_credit' => NULL,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                    'target' => 140,
                ),
            53 =>
                array (
                    'id' => 237,
                    'name' => 'Nông học',
                    'code' => '7620109',
                    'reference_score' => 21.75,
                    'entrance_score' => 21.75,
                    'subjects_combination' => '["B00", "B08", "D07"]',
                    'information' => '<a href="https://tuyensinh.ctu.edu.vn/gioi-thieu-nganh/468-nong-hoc" target="_blank">Xem Thông Tin</a>',
                    'tuition' => '15,2',
                    'total_credit' => NULL,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                    'target' => 100,
                ),
            54 =>
                array (
                    'id' => 238,
                    'name' => 'Bảo vệ thực vật',
                    'code' => '7620112',
                    'reference_score' => 23.0,
                    'entrance_score' => 23.0,
                    'subjects_combination' => '["B00", "B08", "D07"]',
                    'information' => '<a href="https://tuyensinh.ctu.edu.vn/gioi-thieu-nganh/470-bao-ve-thuc-vat" target="_blank">Xem Thông Tin</a>',
                    'tuition' => '15,2',
                    'total_credit' => NULL,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                    'target' => 160,
                ),
            55 =>
                array (
                    'id' => 239,
                    'name' => 'Khoa học môi trường',
                    'code' => '7440301',
                    'reference_score' => 19.5,
                    'entrance_score' => 19.5,
                    'subjects_combination' => '["A00", "A02", "B00", "D07"]',
                    'information' => '<a href="https://tuyensinh.ctu.edu.vn/gioi-thieu-nganh/512-khoa-hoc-moi-truong" target="_blank">Xem Thông Tin</a>',
                    'tuition' => '14,2',
                    'total_credit' => NULL,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                    'target' => 80,
                ),
            56 =>
                array (
                    'id' => 240,
                    'name' => 'Quản lý tài nguyên và môi trường',
                    'code' => '7850101',
                    'reference_score' => 23.0,
                    'entrance_score' => 23.0,
                    'subjects_combination' => '["A00", "A01", "B00", "D07"]',
                    'information' => '<a href="https://tuyensinh.ctu.edu.vn/gioi-thieu-nganh/513-quan-ly-tai-nguyen-va-moi-truong" target="_blank">Xem Thông Tin</a>',
                    'tuition' => '12,6',
                    'total_credit' => NULL,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                    'target' => 120,
                ),
            57 =>
                array (
                    'id' => 241,
                    'name' => 'Kỹ thuật môi trường',
                    'code' => '7520320',
                    'reference_score' => 19.5,
                    'entrance_score' => 19.5,
                    'subjects_combination' => '["A00", "A01", "B00", "D07"]',
                    'information' => '<a href="https://tuyensinh.ctu.edu.vn/gioi-thieu-nganh/511-ky-thuat-moi-truong" target="_blank">Xem Thông Tin</a>',
                    'tuition' => '15,2',
                    'total_credit' => NULL,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                    'target' => 60,
                ),
            58 =>
                array (
                    'id' => 242,
                    'name' => 'Quản lý đất đai',
                    'code' => '7850103',
                    'reference_score' => 25.25,
                    'entrance_score' => 25.25,
                    'subjects_combination' => '["A00", "A01", "B00", "D07"]',
                    'information' => '<a href="https://tuyensinh.ctu.edu.vn/gioi-thieu-nganh/514-quan-ly-dat-dai" target="_blank">Xem Thông Tin</a>',
                    'tuition' => '12,6',
                    'total_credit' => NULL,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                    'target' => 120,
                ),
            59 =>
                array (
                    'id' => 243,
                    'name' => 'Công nghệ rau hoa quả và cảnh quan',
                    'code' => '7620113',
                    'reference_score' => 19.5,
                    'entrance_score' => 19.5,
                    'subjects_combination' => '["A00", "B00", "B08", "D07"]',
                    'information' => '<a href="https://tuyensinh.ctu.edu.vn/gioi-thieu-nganh/469-cong-nghe-rau-hoa-qua-va-canh-quan" target="_blank">Xem Thông Tin</a>',
                    'tuition' => '15,2',
                    'total_credit' => NULL,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                    'target' => 80,
                ),
            60 =>
                array (
                    'id' => 244,
                    'name' => 'Khoa học đất',
                    'code' => '7620103',
                    'reference_score' => 19.5,
                    'entrance_score' => 19.5,
                    'subjects_combination' => '["A00", "B00", "B08", "D07"]',
                    'information' => '<a href="https://tuyensinh.ctu.edu.vn/gioi-thieu-nganh/907-quan-ly-dat-va-cong-nghe-phan-bon" target="_blank">Xem Thông Tin</a>',
                    'tuition' => '15,2',
                    'total_credit' => NULL,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                    'target' => 60,
                ),
            61 =>
                array (
                    'id' => 245,
                    'name' => 'Nuôi trồng thủy sản',
                    'code' => '7620301',
                    'reference_score' => 22.5,
                    'entrance_score' => 22.5,
                    'subjects_combination' => '["A00", "B00", "B08", "D07"]',
                    'information' => '<a href="https://tuyensinh.ctu.edu.vn/gioi-thieu-nganh/519-nuoi-trong-thuy-san" target="_blank">Xem Thông Tin</a>',
                    'tuition' => '15,2',
                    'total_credit' => NULL,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                    'target' => 220,
                ),
            62 =>
                array (
                    'id' => 246,
                    'name' => 'Bệnh học thủy sản',
                    'code' => '7620302',
                    'reference_score' => 19.5,
                    'entrance_score' => 19.5,
                    'subjects_combination' => '["A00", "B00", "B08", "D07"]',
                    'information' => '<a href="https://tuyensinh.ctu.edu.vn/gioi-thieu-nganh/520-benh-hoc-thuy-san" target="_blank">Xem Thông Tin</a>',
                    'tuition' => '15,2',
                    'total_credit' => NULL,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                    'target' => 100,
                ),
            63 =>
                array (
                    'id' => 247,
                    'name' => 'Quản lý thủy sản',
                    'code' => '7620305',
                    'reference_score' => 19.5,
                    'entrance_score' => 19.5,
                    'subjects_combination' => '["A00", "B00", "B08", "D07"]',
                    'information' => '<a href="https://tuyensinh.ctu.edu.vn/gioi-thieu-nganh/521-quan-ly-thuy-san" target="_blank">Xem Thông Tin</a>',
                    'tuition' => '15,2',
                    'total_credit' => NULL,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                    'target' => 100,
                ),
            64 =>
                array (
                    'id' => 248,
                    'name' => 'Toán ứng dụng',
                    'code' => '7460112',
                    'reference_score' => 22.0,
                    'entrance_score' => 22.0,
                    'subjects_combination' => '["A00", "A01", "A02", "B00"]',
                    'information' => '<a href="https://tuyensinh.ctu.edu.vn/gioi-thieu-nganh/885-toan-ung-dung.html" target="_blank">Xem Thông Tin</a>',
                    'tuition' => '15,2',
                    'total_credit' => NULL,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                    'target' => 80,
                ),
            65 =>
                array (
                    'id' => 249,
                    'name' => 'Vật lý kỹ thuật',
                    'code' => '7520401',
                    'reference_score' => 19.5,
                    'entrance_score' => 19.5,
                    'subjects_combination' => '["A00", "A01", "A02", "C01"]',
                    'information' => '<a href="https://tuyensinh.ctu.edu.vn/gioi-thieu-nganh/528-vat-ly-ky-thuat" target="_blank">Xem Thông Tin</a>',
                    'tuition' => '15,2',
                    'total_credit' => NULL,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                    'target' => 40,
                ),
            67 =>
                array (
                    'id' => 251,
                    'name' => 'Hóa dược',
                    'code' => '7720203',
                    'reference_score' => 28.0,
                    'entrance_score' => 28.0,
                    'subjects_combination' => '["A00", "B00", "C02", "D07"]',
                    'information' => '<a href="https://tuyensinh.ctu.edu.vn/gioi-thieu-nganh/745-hoa-duoc" target="_blank">Xem Thông Tin</a>',
                    'tuition' => '19,5',
                    'total_credit' => NULL,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                    'target' => 80,
                ),
            68 =>
                array (
                    'id' => 252,
                    'name' => 'Sinh học',
                    'code' => '7420101',
                    'reference_score' => 19.5,
                    'entrance_score' => 19.5,
                    'subjects_combination' => '["A02", "B00", "B03", "B08"]',
                    'information' => '<a href="https://tuyensinh.ctu.edu.vn/gioi-thieu-nganh/766-sinh-hoc" target="_blank">Xem Thông Tin</a>',
                    'tuition' => '14,2',
                    'total_credit' => NULL,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                    'target' => 40,
                ),
            69 =>
                array (
                    'id' => 253,
                    'name' => 'Sinh học ứng dụng',
                    'code' => '7420203',
                    'reference_score' => 19.5,
                    'entrance_score' => 19.5,
                    'subjects_combination' => '["A00", "A01", "B00", "B08"]',
                    'information' => '<a href="https://tuyensinh.ctu.edu.vn/gioi-thieu-nganh/751-sinh-hoc-ung-dung" target="_blank">Xem Thông Tin</a>',
                    'tuition' => '14,2',
                    'total_credit' => NULL,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                    'target' => 40,
                ),
            70 =>
                array (
                    'id' => 254,
                    'name' => 'Công nghệ sinh học',
                    'code' => '7420201',
                    'reference_score' => 25.75,
                    'entrance_score' => 25.75,
                    'subjects_combination' => '["A00", "B00", "B08", "D07"]',
                    'information' => '<a href="https://tuyensinh.ctu.edu.vn/gioi-thieu-nganh/546-cong-nghe-sinh-hoc" target="_blank">Xem Thông Tin</a>',
                    'tuition' => '14,2',
                    'total_credit' => NULL,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                    'target' => 120,
                ),
            71 =>
                array (
                    'id' => 255,
                    'name' => 'Văn học',
                    'code' => '7229030',
                    'reference_score' => 25.75,
                    'entrance_score' => 25.75,
                    'subjects_combination' => '["C00", "D01", "D14", "D15"]',
                    'information' => '<a href="https://tuyensinh.ctu.edu.vn/gioi-thieu-nganh/887-van-hoc" target="_blank">Xem Thông Tin</a>',
                    'tuition' => '12,6',
                    'total_credit' => NULL,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                    'target' => 80,
                ),
            72 =>
                array (
                    'id' => 256,
                    'name' => 'Việt Nam học',
                    'code' => '7310630',
                    'reference_score' => 27.25,
                    'entrance_score' => 27.25,
                    'subjects_combination' => '["C00", "D01", "D14", "D15"]',
                    'information' => '<a href="https://tuyensinh.ctu.edu.vn/gioi-thieu-nganh/530-viet-nam-hoc" target="_blank">Xem Thông Tin</a>',
                    'tuition' => '12,6',
                    'total_credit' => NULL,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                    'target' => 80,
                ),
            73 =>
                array (
                    'id' => 257,
                    'name' => 'Việt nam học - học tại khu Hòa An',
                    'code' => '7310630H',
                    'reference_score' => 24.75,
                    'entrance_score' => 24.75,
                    'subjects_combination' => '["C00", "D01", "D14", "D15"]',
                    'information' => '<a href="https://tuyensinh.ctu.edu.vn/gioi-thieu-nganh/842-viet-nam-hoc-h" target="_blank">Xem Thông Tin</a>',
                    'tuition' => '12,6',
                    'total_credit' => NULL,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                    'target' => 40,
                ),
            74 =>
                array (
                    'id' => 258,
                    'name' => 'Ngôn ngữ Anh',
                    'code' => '7220201',
                    'reference_score' => 27.75,
                    'entrance_score' => 27.75,
                    'subjects_combination' => '["D01", "D14", "D15"]',
                    'information' => 'Ngành Ngôn ngữ Anh có 2 chuyên ngành:<br>Ngôn ngữ Anh: <a href="https://tuyensinh.ctu.edu.vn/gioi-thieu-nganh/772-ngon-ngu-anh-ngon-ngu-anh" target="_blank">Xem Thông Tin</a><br>Phiên dịch-Biên dịch tiếng Anh: <a href="https://tuyensinh.ctu.edu.vn/gioi-thieu-nganh/773-ngon-ngu-anh-phien-dich-bien-dich-tieng-anh" target="_blank">Xem Thông Tin</a>',
                    'tuition' => '12,6',
                    'total_credit' => NULL,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                    'target' => 100,
                ),
            75 =>
                array (
                    'id' => 259,
                    'name' => 'Ngôn ngữ Anh - học tại Khu Hòa An',
                    'code' => '7220201H',
                    'reference_score' => 26.0,
                    'entrance_score' => 26.0,
                    'subjects_combination' => '["D01", "D14", "D15"]',
                    'information' => '<a href="https://tuyensinh.ctu.edu.vn/gioi-thieu-nganh/843-ngon-ngu-anh-ngon-ngu-anh-h" target="_blank">Xem Thông Tin</a>',
                    'tuition' => '12,6',
                    'total_credit' => NULL,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                    'target' => 40,
                ),
            76 =>
                array (
                    'id' => 260,
                    'name' => 'Ngôn ngữ pháp',
                    'code' => '7220203',
                    'reference_score' => 24.0,
                    'entrance_score' => 24.0,
                    'subjects_combination' => '["D01", "D03", "D14", "D64"]',
                    'information' => '<a href="https://tuyensinh.ctu.edu.vn/gioi-thieu-nganh/533-ngon-ngu-phap" target="_blank">Xem Thông Tin</a>',
                    'tuition' => '12,6',
                    'total_credit' => NULL,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                    'target' => 40,
                ),
            77 =>
                array (
                    'id' => 261,
                    'name' => 'Thông tin - thư viện',
                    'code' => '7320201',
                    'reference_score' => 21.5,
                    'entrance_score' => 21.5,
                    'subjects_combination' => '["A01", "D01", "D03", "D29"]',
                    'information' => '<a href="https://tuyensinh.ctu.edu.vn/gioi-thieu-nganh/532-thong-tin-hoc" target="_blank">Xem Thông Tin</a>',
                    'tuition' => '12,6',
                    'total_credit' => NULL,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                    'target' => 60,
                ),
            78 =>
                array (
                    'id' => 262,
                    'name' => 'Triết học',
                    'code' => '7229001',
                    'reference_score' => 24.0,
                    'entrance_score' => 24.0,
                    'subjects_combination' => '["C00", "C19", "D14", "D15"]',
                    'information' => '<a href="https://tuyensinh.ctu.edu.vn/gioi-thieu-nganh/538-triet-hoc" target="_blank">Xem Thông Tin</a>',
                    'tuition' => '12,6',
                    'total_credit' => NULL,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                    'target' => 40,
                ),
            79 =>
                array (
                    'id' => 263,
                    'name' => 'Chính trị học',
                    'code' => '7310201',
                    'reference_score' => 26.0,
                    'entrance_score' => 26.0,
                    'subjects_combination' => '["C00", "C19", "D14", "D15"]',
                    'information' => '<a href="https://tuyensinh.ctu.edu.vn/gioi-thieu-nganh/539-chinh-tri-hoc" target="_blank">Xem Thông Tin</a>',
                    'tuition' => '12,6',
                    'total_credit' => NULL,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                    'target' => 40,
                ),
            80 =>
                array (
                    'id' => 264,
                    'name' => 'Xã hội học',
                    'code' => '7310301',
                    'reference_score' => 26.25,
                    'entrance_score' => 26.25,
                    'subjects_combination' => '["A01", "C00", "C19", "D01"]',
                    'information' => '<a href="https://tuyensinh.ctu.edu.vn/gioi-thieu-nganh/565-xa-hoi-hoc.html" target="_blank">Xem Thông Tin</a>',
                    'tuition' => '12,6',
                    'total_credit' => NULL,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                    'target' => 80,
                )
            )
        );
    }
}
